# Generated by Django 3.1.7 on 2022-08-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='logo',
            field=models.ImageField(default='no_picture.png', upload_to='transport_logo'),
        ),
    ]
